### ISSUE TITLE
proposal: increase scope to cover stl

### ISSUE THREAD

**Issue by timotheecour** [kaushalmodi/std_vector#3]
idea:
* turn this repo into a single monorepo `cpp_stl` (which would grow over time; IMO next big thing is `std::string`) (and yes, I know about `My goal is not to create a wrapper that wraps to 100% of the C++ library` :) )

* add individual nimble packages to avoid pulling "the world" when you just care about `import std_vector`, eg:

cpp_stl.git:
```nim
nimble install -y "http://github.com/kaushalmodi/cpp_stl?subdir=std_vector" 
nimble install -y "http://github.com/kaushalmodi/cpp_stl?subdir=std_string" 
nimble install -y "http://github.com/kaushalmodi/cpp_stl?subdir=std_algorithm" 
nimble install -y "http://github.com/kaushalmodi/cpp_stl?subdir=std_common"  # common stuff
nimble install -y "http://github.com/kaushalmodi/cpp_stl"  # install "the world" (not 100% sure whether this last one can work, probably should)
```
ideally these can share all the code that needs to be shared (eg all could depend on `std_common`) to keep it DRY

* not clear whether 

## links
* eg of a monorepo: https://github.com/genotrance/nimtreesitter
`nimble install -y "http://github.com/genotrance/nimtreesitter?subdir=treesitter"`

## question:
yes we use `std::vector` but std is also "overloaded" by nim's `std`, I wonder whether the prefix stl would be more suiting for C++ standard template library? no possibility for confusion there

**Comment by kaushalmodi** [comment]
A Nim cpp_stl mono-repo already exists at https://github.com/BigEpsilon/nim-cppstl/tree/master/src/cppstl.

I discovered that mid-way between when I started this repo and the current state. But then I kept on developing this project as I have zero C++ knowledge and  I needed the runnableExamples for my own reference.

Given that I have no C++ knowledge, I doubt if I can head a cpp_stl mono repo.

An addendum to your idea.. move this repo to a mono repo in a Github Organization, and I add you as a contributor. Would you help grow that library?

**Comment by timotheecour** [comment]
> already exists at 

ooooo... I wasn't aware of that...

> An addendum to your idea.. move this repo to a mono repo in a Github Organization, and I add you as a contributor. Would you help grow that library?

sure, but I can't make any promise on how much I'll have time to contribute; but ya the more the merrier, STL is really important for interop.

The part that worries me is duplication of effort with https://github.com/BigEpsilon/nim-cppstl (as well as the unavoidable incompatibilities if there are 2 different libs going after the same goal). Can't we merge those 2 libs? from a quick look, I can already see things that are better in yours (eg runnableExamples, doc comments) and things that are better in his (eg it already has `swap`; more generally it has more procs mapped, eg `capacity`)

do you mind if I add him to this conversation to see if he's interested in a joined repo so all efforts are combined instead ?

**Comment by kaushalmodi** [comment]
Hello @BigEpsilon, I am pinging you here where that conversation to merge our repos began :). Looking forward to a merger of our efforts.

**Comment by timotheecour** [comment]
also note that nimterop could help here eventually but it doesn't look anywhere close yet

**Comment by kaushalmodi** [comment]
Closing this issue as now this repo content is merged into nim-cppstl in https://github.com/Clonkk/nim-cppstl/pull/13 .
