### ISSUE TITLE
misc feedback part 2

### ISSUE THREAD

**Issue by timotheecour** [kaushalmodi/std_vector#9]
- [x] newVector => initVector since it's an object, not ref

**Comment by timotheecour** [comment]
- [ ] not super sure about this one:

```
proc `[]`*[T](v: Vector[T], idx: SizeType): var T {.importcpp: "#[#]".} =
```

=> fishy; take v by var?

```
proc `[]`*[T](v: Vector[T], idx: SizeType): lent T {.importcpp: "#[#]".} =
proc `[]`*[T](v: var Vector[T], idx: SizeType): var T {.importcpp: "#[#]".} =
```

**Comment by kaushalmodi** [comment]
> proc `[]`*[T](v: Vector[T], idx: SizeType): lent T {.importcpp: "#[#]".} =

What does "lent T" mean?

**Comment by kaushalmodi** [comment]
> newVector => initVector since it's an object, not ref

Done in https://github.com/kaushalmodi/std_vector/commit/1eb2e9e6de2687c293724b20b27cdcfff8edcfae

**Comment by timotheecour** [comment]
> What does "lent T" mean?

it's here https://nim-lang.github.io/Nim/destructors.html#lent-type

the fact that you can't find it easily is a bug (or missing feature) in docgen; simply searching for `lent` in search (dochack) or theindex should bring up that entry, but doesn't.

my plans (WIP sketch in https://github.com/timotheecour/Nim/issues/228) for that is to allow definitions entries to appear anywhere in doc comments (rst or not), with a single definition per entry.

We already have `idx` as in ```## Marks a sequence `s` as `shallow`:idx:. Subsequent assignment``` but this indicates a reference (and points to an entry in theindex), not a definition, what's lacking is a way to point to the one-definition:
in short we need a way to disinguish between reference (``` `shallow`:idx: ```) and definition (``` ``` `shallow`:def: ```)

This could be used to reference any location, not just a nim symbol (which do generate index entry, altough I don't like the way it works for overloads), but also things like runnableExamples; so this should work too:
```nim
# this will create an entry in theindex for `lent-usage`
runnableExamples:
  ## `lent-usage`:def:, see also `lent`:idx:
  code...
```

Note that titles in rst currently don't give rise to theindex entries, but even if they did it wouldn't be great because titles can change and are cumbersome to reference to, eg:
doc/destructors.rst)
```rst
Lent type
=========

``proc p(x: sink T)`` means that the proc ``p`` takes ownership of ``x``.
To eliminate even more creation/copy <-> destruction pairs, a proc's return ...
```

option 1:
```rst
[lent](Lent type)
=================
...
```

option 1:
```
Lent type lent:def:
===================
...
```

**Comment by kaushalmodi** [comment]
In cppstl repo, there's no `lent T` in return type. But at least there are two variants (var and non-var) for `[]` and few other procs: https://github.com/Clonkk/nim-cppstl/blob/29777c7137efa9f13de01b058286d4e16c8ae104/cppstl/std_vector.nim#L358-L364
